# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: mysql2
  encoding: utf8
  reconnect: false
  pool: 5
  host: 10.131.137.216
  port: 3306
  username: root
  password: bkiOBN51

development:
  <<: *default
  database: books_development
test:
  <<: *default
  database: books_test

production:
  <<: *default
  database: books_producion
